In [42]:
%load_ext autoreload
%autoreload 2
import jax
from jax import random
from environments import RodentSingleClipTrack
import numpy as np
import mediapy as media
import jax.numpy as jp

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [45]:
params = {
    "scale_factor": .9,
    "solver": "cg",
    "iterations": 6,
    "ls_iterations": 3,
    "clip_path": "12_22_1_250_clip_0.p",
    "end_eff_names": [
        "foot_L",
        "foot_R",
        "hand_L",
        "hand_R",
    ],
}

# Creating env objects

In [46]:
env = RodentSingleClipTrack(params)

/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitation-Main/.brax-imitation/lib/python3.10/site-packages/brax/io/mjcf.py:344: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  link = jax.tree_map(lambda x: x[1:].copy(), link)
/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitation-Main/.brax-imitation/lib/python3.10/site-packages/brax/io/mjcf.py:374: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  motion = jax.tree_map(lambda *x: np.concatenate(x), *motions)
/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitation-Main/.brax-imitation/lib/python3.10/site-packages/brax/io/mjcf.py:378: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  limit = jax.tree_map(lambda *x: np.concatenate(x), *limits)
/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitatio

In [47]:
key = random.PRNGKey(0)
jit_step = jax.jit(env.step)
jit_reset = jax.jit(env.reset)
# next = env.step(state, random.uniform(key, shape=(env.sys.nu,)))

In [48]:
type(env._ref_traj)

mocap_preprocess.ReferenceClip

In [49]:
n = env.reset(key)

/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitation-Main/.brax-imitation/lib/python3.10/site-packages/mujoco/mjx/_src/scan.py:65: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  return jax.tree_map(take, obj)
/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitation-Main/.brax-imitation/lib/python3.10/site-packages/mujoco/mjx/_src/scan.py:65: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  return jax.tree_map(take, obj)
/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitation-Main/.brax-imitation/lib/python3.10/site-packages/mujoco/mjx/_src/scan.py:65: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  return jax.tree_map(take, obj)
/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitation-Main/.brax-imitation/lib/python3.10/site-packages/mujoco

In [50]:
# res = jax.tree_util.tree_map(
#     lambda x: jax.lax.dynamic_slice_in_dim(x, 3, 4, axis=1),
#     env._ref_traj,
# )

In [51]:
jax.tree_util.tree_map(
    lambda x: print(x.shape),
    env._ref_traj,
)

(250, 3)
(250, 5, 3)
(250, 18, 3)
(250, 18, 4)
(250, 3)
(250, 4, 3)
(250, 67)
(250, 67)
(0,)
(250, 3)
(250, 4)
(0,)
(250, 3)


ReferenceClip(angular_velocity=None, appendages=None, body_positions=None, body_quaternions=None, center_of_mass=None, end_effectors=None, joints=None, joints_velocity=None, markers=None, position=None, quaternion=None, scaling=None, velocity=None)

In [52]:
env._ref_traj.body_positions[:,env.body_idxs]

Array([[[-0.05157034,  0.3405091 ,  0.07103304],
        [-0.04423911,  0.297583  ,  0.05947985],
        [-0.05854973,  0.29726464,  0.05947506],
        ...,
        [-0.06766652,  0.3676939 ,  0.05456821],
        [-0.05300185,  0.35287777,  0.0384187 ],
        [-0.06718285,  0.3718082 ,  0.01327727]],

       [[-0.05444217,  0.3449859 ,  0.07158838],
        [-0.05279249,  0.30190387,  0.0614456 ],
        [-0.06676881,  0.30457118,  0.05988254],
        ...,
        [-0.0607067 ,  0.37427917,  0.05398194],
        [-0.05153117,  0.3574425 ,  0.03587908],
        [-0.05690969,  0.38318592,  0.01352061]],

       [[-0.05978363,  0.35593086,  0.07326452],
        [-0.06929351,  0.3148967 ,  0.06476209],
        [-0.08140896,  0.32034692,  0.05943235],
        ...,
        [-0.052885  ,  0.3811076 ,  0.05077108],
        [-0.04858348,  0.36400667,  0.03116415],
        [-0.0398935 ,  0.39113626,  0.01167   ]],

       ...,

       [[ 0.04417997,  0.12506871,  0.06885403],
        [ 0

In [53]:
env._ref_traj.angular_velocity.shape

(250, 3)

In [54]:
# def slice_arrays(start_index, end_index):
#     def slicer(x):
#         if isinstance(x, jp.ndarray):
#             return x[..., start_index:end_index]
#         return x
#     return slicer

# sliced_tree = jax.tree_map(slice_arrays(0, 5), env._ref_traj)
# sliced_tree.body_positions.shape

In [55]:
# start_index = 0
# end_index = 5
# sliced_clip = env._ref_traj.slice_clip(start_index, end_index)
# sliced_clip.center_of_mass.shape

# Creating state objects & reset_fn, get_obs_fn
`reset_fn` and `get_obs_fn` is called when initilizing the environment and creating the state object

In [56]:
rng = random.PRNGKey(0)
state = env.reset(rng)

/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitation-Main/.brax-imitation/lib/python3.10/site-packages/mujoco/mjx/_src/scan.py:65: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  return jax.tree_map(take, obj)
/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitation-Main/.brax-imitation/lib/python3.10/site-packages/mujoco/mjx/_src/scan.py:65: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  return jax.tree_map(take, obj)
/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitation-Main/.brax-imitation/lib/python3.10/site-packages/mujoco/mjx/_src/scan.py:65: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  return jax.tree_map(take, obj)
/Users/kevinb/Desktop/salk/rodent/VNL-Brax-Imitation-Main/.brax-imitation/lib/python3.10/site-packages/mujoco

In [22]:
state.info['start_frame']

Array(56, dtype=int32)

In [23]:
env._ref_traj.velocity[:, state.info['start_frame']]

Array([ 0.40821564, -0.20567179, -0.11344627], dtype=float32)

In [87]:
state.pipeline_state.xpos[:,0] # all x values
state.pipeline_state.xpos.shape

(66, 3)

In [86]:
env._ref_traj.body_positions.shape

(250, 18, 3)

In [26]:
state.obs.shape

(1747,)

end effector position

In [63]:
state.pipeline_state.xpos[jp.array(env._end_eff_idx)]

Array([[-0.00912952,  0.4411053 ,  0.01141115],
       [-0.03021844,  0.414083  ,  0.01621009],
       [ 0.0780039 ,  0.40200663,  0.01433735],
       [ 0.08267315,  0.36600125,  0.02249428]], dtype=float32)

In [28]:
env._ref_traj.end_effectors.shape

(12, 250)

# Creating step_fn, reward_fn, & termination_fn
`step_fn`, which calls `reward_fn` & `termination_fn` is only used when actually making action, not when setting up environment and state object

In [29]:
# rollout = [state.pipeline_state]
# ctrl = jax.numpy.array(np.random.uniform(-1,1, env.sys.nu))
# state = env.step(state, ctrl)
# rollout.append(state.pipeline_state)

In [30]:
# media.show_video(env.render(rollout,camera='close_profile'), fps=1.0 / env.dt)

In [71]:
next = jit_reset(key)
print("starting rollout")
mu = 0
sigma = .1
rollout = []
for _ in range(500):
    next = jit_step(next, mu + sigma * random.normal(key, shape=(env.sys.nu,)))
    rollout.append(next)

starting rollout


In [72]:
import mediapy as media
import os

os.environ["MUJOCO_GL"] = "glfw"
rollout_data = [s.pipeline_state for s in rollout]

video = env.render(rollout_data, camera='side_alt', height=500, width=500)

media.show_video(video, fps=1.0 / env.dt)